"""
Django settings for zentao project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR_PARENT = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kjm*-kip!tgy1n4o&8s&dbu1^h#lrv05tdiv@l0rcqh+ehxcv='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 处理websocket
    'channels',
    # celery定时任务
    'django_celery_results',
    'django_celery_beat',
    # 自定义
    'web.apps.WebConfig',
    'testapp.apps.TestappConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.check_session.check_session'
]

ROOT_URLCONF = 'zentao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # 返回的结果会更新到render的字典里
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zentao.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_TZ = False
USE_I18N = True
USE_L10N = True

# 影响自动生成数据库时间字段
# USE_TZ = True   创建UTC时间写入到数据库
# USE_TZ = False  根据TIME_ZONE设置的时区进行创建时间并写入数据库

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# 添加额外的static目录，因为默认是各个app下的static
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 静态资源存储路径
STATIC_ROOT = BASE_DIR_PARENT / "allstatic"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NO_SESSION_CHECK_URLS = [
    '/account/register/',
    '/account/login/',
    '/account/logout/',
    '/account/get_checkcode/',
    '/account/send/sms/',
    '/account/index/',
    '/account/get_random_username/',
    '/admin/'
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

FILE_UPLOAD_MAX_MEMORY_SIZE_ERROR = '上传文件大小上限：1MB'
# DATA_UPLOAD_MAX_MEMORY_SIZE = 0.1 * 1024 * 1024  # 可选，比如 10MB


FILE_UPLOAD_HANDLERS = [
    'utils.handles.MaxSizeFileUploadHandler',
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# 讯飞星火大模型  SPARK MAX
SPARK_API_PASSWORD = 'ldqTwpvzYwBAqDsltIqi:qHRalFIhSFxfWTUHqgIi'

# channels 相关配置 ( installed app )
ASGI_APPLICATION = 'zentao.asgi.application'

# 保存用户 ？
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': ['redis://127.0.0.1:6379/6', ]
        }
    }
}

# 邮箱配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True

EMAIL_HOST_USER = '2597843280@qq.com'
EMAIL_HOST_PASSWORD = 'ravspywscpefecdj'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# simpleui 配置
SIMPLEUI_HOME_INFO = False  # 关闭首页右侧广告
SIMPLEUI_ANALYSIS = False  # 关闭simpleui内置的使用分析

# # ceelry 配置 # #
# Celery配置
# # Broker配置,使用Redis作为消息中间件
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/7'
# # BACKEND配置,使用redis
# CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/8'
CELERY_RESULT_BACKEND = 'django-db'  # 使用数据库作为结果存储
# # 结果序列化方案
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# # 任务结果过期时间,秒
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
# # celery 时区配置
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = False  # True：Celery 使用 UTC 时间  False：Celery使用本地时间，周期任务调度基于本地时区计算
CELERY_RESULT_EXTENDED = True
CELERY_TASK_IGNORE_RESULT = False
# # eager模式配置
# CELERY_TASK_ALWAYS_EAGER = True  # Celery 在调用任务时，不再将任务发送到消息队列（broker），而是直接在本地、同步执行
# CELERY_TASK_EAGER_PROPAGATES = True  # 控制任务在 eager 模式下 出现异常时的行为 False（默认）：任务出错时，异常会被捕获并存储在结果对象中，不会直接抛出。 True：任务一旦出错，异常会立即向上传播（抛出），就像普通函数调用一样。

# CELERY_ACKS_LATE = True  # 不提前确认任务完成，只有在任务成功执行后才确认。
# CELERY_TASK_TIME_LIMIT = 3
DJANGO_CELERY_BEAT_TZ_AWARE = False

# celery-beat配置
# CELERYBEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

CELERY_TASK_SOFT_TIME_LIMIT = 10

try:
    from .local_settings import *
except ImportError as e:
    pass
