"""
Django settings for zentao project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR_PARENT = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kjm*-kip!tgy1n4o&8s&dbu1^h#lrv05tdiv@l0rcqh+ehxcv='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',

    'web.apps.WebConfig',
    'testapp.apps.TestappConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.check_session.check_session'
]

ROOT_URLCONF = 'zentao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # 返回的结果会更新到render的字典里
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zentao.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


USE_I18N = True

USE_L10N = True

LANGUAGE_CODE = 'zh-hans'

#
TIME_ZONE = 'Asia/Shanghai'

# 影响自动生成数据库时间字段
# USE_TZ = True   创建UTC时间写入到数据库
# USE_TZ = False  根据TIME_ZONE设置的时区进行创建时间并写入数据库
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# 添加额外的static目录，因为默认是各个app下的static
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 静态资源存储路径
STATIC_ROOT = BASE_DIR_PARENT / "allstatic"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NO_SESSION_CHECK_URLS = [
    '/account/register/',
    '/account/login/',
    '/account/logout/',
    '/account/get_checkcode/',
    '/account/send/sms/',
    '/account/index/',
    '/account/get_random_username/',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

FILE_UPLOAD_MAX_MEMORY_SIZE_ERROR = '上传文件大小上限：1MB'
# DATA_UPLOAD_MAX_MEMORY_SIZE = 0.1 * 1024 * 1024  # 可选，比如 10MB


FILE_UPLOAD_HANDLERS = [
    'utils.handles.MaxSizeFileUploadHandler',
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# 讯飞星火大模型  SPARK MAX
SPARK_API_PASSWORD = 'ldqTwpvzYwBAqDsltIqi:qHRalFIhSFxfWTUHqgIi'

# channels 相关配置 ( installed app )
ASGI_APPLICATION = 'zentao.asgi.application'

# 保存用户 ？
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': ['redis://127.0.0.1:6379/6',]
        }
    }
}

try:
    from .local_settings import *
except ImportError as e:
    pass
